### PR TITLE
Apply strtolower before ucfirst on Capitalize

### PR DESCRIPTION
**Pull request by johnpaulmedina**
The filter with just ucfirst fails if the input is all capitalized. In order for this to properly work you must lowercase everything, then apply the ucfirst

### CODE REVIEW

**Comment by johnpaulmedina** [comment]
Fixed issue where multiple Sanitizers were overwriting the last sanitizer with the original input value
Added a TitleCase sanitizer

**Comment by ArondeParon** [comment]
First of all: thanks for the PR! It's always fun to see a pull request because it reminds me that people actually _use_ this package, which I sometimes tend to forget 😅 

As for your improvements:

> The filter with just ucfirst fails if the input is all capitalized. In order for this to properly work you must lowercase everything, then apply the ucfirst

I am not sure that I agree on this one. `ucfirst()` works like this as well. If this is desired behavior, I would probably expect a `LowerCase` filter to be chained with `Capitalize`.

> Fixed issue where multiple Sanitizers were overwriting the last sanitizer with the original input value
> Added a TitleCase sanitizer

Do you have an example of this behavior? I have not had the time to set up a test case, but would love to see how this bug occurs in a user scenario. Perhaps this is also good material for an additional test.

**Comment by johnpaulmedina** [comment]
You're welcome. 

The way you describe the `ucfirst` behavior and chaining them - yes I agree in that sense. The reason for my initial logic is just that when you are depending on both a developer and an end-user's input then logic doesn't necessarily always behave the way the developer intends. 

I actually created another filter for 'Title Case' which essentially would meet right in the middle of both our views. Simple enough I believe. 

In regards to the sanitizer at least on the most current version of Laravel:

```
...
return $this->replace($input);
```

This was sitting outside of the foreach loop. At the start of the `sanitize()` function you are assigning `$input = $this->all();` which is an array; later in the foreach loop you are calling

```
...
Arr::set($input, $formKey, $sanitizer->sanitize($this->input($formKey, null)));
```

Since you are running `$sanitizer->sanitize()` on `$this->input($formKey, null)` you are always grabbing from the requests input and not the assigned input array. The `\Illuminate\Support\Arr::set` method is over writing your assigned `$input` array but logically it always being overwritten on chained sanitizers by the `$requests` input and not the previously assigned array value. 

I made a few other modifications too if you like I can do a PR as well. Since Laravel supports `array` values on form inputs I modified the filters you provided and the ones I made to detect if an array and then apply the sanitizer on each subsequent value.

Example POST
```
first_name[0]=John%20Paul&first_name[1]=Aaron
```
If we wanted to apply an `Uppercase::class` sanitizer on `first_name` it won't apply to all `first_name` values. Detecting an array applies on any number of subsequent array values and if not an array defaults back to a `string` single value sanitizer. This is helpful on dynamic input forms where an end-user can create more of a field.

**Comment by ArondeParon** [comment]
Thanks for the clarification!

For now, I will include the bug fix for multiple sanitizers in https://github.com/ArondeParon/laravel-request-sanitizer/pull/19. Thanks for catching this bug!

In the referenced PR I have also added a unit test to prove that it now works.

As for the other functionality:

- The `strtolower` before `capitalize` seems very implementation specific, so I am excluding it from this PR.
- The `TitleCase` sanitizer looks okay to me. Feel free to add it in a separate PR. Please include a test for the sanitizer as well.
- The behavior that looks for the "url" string in the form keys feels very specific to me. I don't think that this should be in the library, but rather in the implmentation.
- The wildcard support looks interesting! The change is relatively large though, so I would rather see it in a separate PR, with an explanation of the problem that this solves and accompanying unit tests to prove that everything works as intended (IE: we want to prevent that wildcard sanitizers conflict in an unexpected way with key-specific sanitizers).

Thanks again for the bugfix!

**Pull request closed without merging**
